start = filestructure_commands find_command;
find_command = env_variables ws program command | program command;
program = "timeout 0.5s find";

file_name = "foo" | "bar" | "link";
directory_name = "dir1" | "directory2" | "dir2" | "dir3";
all_directory_name = directory_name | "." | "..";
dirpath = all_directory_name | all_directory_name "/" dirpath;
filepath = dirpath "/" file_name | file_name;
pathname = filepath | dirpath;

filestructure_commands = empty | filestructure_command "; " filestructure_commands;
filestructure_command = touch | mkdir | ln;
touch = "al_touch " file_name;
mkdir = "mkcd " directory_name "; " filestructure_commands "al_popd";
ln = ln_file | ln_dir;
ln_file = "al_ln -s " pathname ws file_name;
ln_dir = "al_ln -s " pathname ws directory_name;

env_variables = env_options ;
env_options = locale_options | posix | intl_msg | time_zone ;
intl_msg = "NLSPATH=" dirpath;
time_zone = "TZ=" time_zones;
time_zones = "Africa/Abidjan" | "Africa/Accra" | "Africa/Nairobi" | "Africa/Algiers" | "Africa/Asmara" | "Africa/Nairobi" | "Africa/Bamako" | "Africa/Abidjan" | "Africa/Bangui" | "Africa/Lagos" | "Africa/Banjul" | "Africa/Bissau" | "Africa/Blantyre" | "Africa/Maputo" | "Africa/Brazzaville" | "Africa/Lagos" | "Africa/Bujumbura" | "Africa/Maputo" | "Africa/Cairo" | "Africa/Casablanca" | "US/Alaska" | "America/Anchorage" | "US/Aleutian" | "America/Adak" | "US/Arizona" | "America/Phoenix" | "US/Central" | "America/Chicago" | "US/Eastern" | "US/East-Indiana" | "America/Indiana/Indianapolis" | "US/Hawaii" | "Pacific/Honolulu" | "US/Indiana-Starke" | "America/Indiana/Knox" | "US/Michigan" | "America/Detroit" | "US/Mountain" | "America/Denver" | "US/Pacific" | "US/Pacific-New" | "US/Samoa" | "Europe/Amsterdam" | "Europe/Andorra" | "Europe/Astrakhan" | "Europe/Athens" | "Europe/Belfast" | "Europe/London" | "Europe/Belgrade" | "Europe/Berlin" | "Europe/Bratislava" | "Europe/Brussels" | "Europe/Bucharest" | "Europe/Budapest" | "Europe/Busingen" | "Europe/Chisinau" | "Europe/Copenhagen" | "Europe/Dublin" | "Europe/Gibraltar" | "Europe/Guernsey" | "Europe/Helsinki" | "Europe/Istanbul" | "Europe/Jersey" | "Europe/Kaliningrad" | "Europe/Kiev" | "Europe/Kirov" | "Europe/Lisbon" | "Europe/Ljubljana" | "Europe/London" | "Europe/Luxembourg" | "Europe/Madrid" | "Europe/Malta" | "Europe/Mariehamn" | "Europe/Minsk" | "Europe/Monaco" | "Europe/Moscow" | "Asia/Nicosia" | "Europe/Oslo" | "Europe/Paris" | "Europe/Podgorica" | "Europe/Prague" | "Europe/Riga" | "Europe/Rome" | "Europe/Samara" | "Europe/Rome" | "Europe/Sarajevo" | "Europe/Saratov" | "Europe/Simferopol" | "Europe/Skopje" | "Europe/Sofia" | "Europe/Stockholm" | "Europe/Tallinn" | "Europe/Tirane" | "Europe/Tiraspol" | "Europe/Ulyanovsk" | "Europe/Uzhgorod" | "Europe/Vaduz" | "Europe/Vatican" | "Europe/Vienna" | "Europe/Vilnius" | "Europe/Volgograd" | "Europe/Warsaw" | "Europe/Zagreb" | "Europe/Zaporozhye";
locale_options = lc_all ws lc_options ws lang; 
lc_options = lc_collate | lc_ctype | lc_messages ;
lc_collate = "LC_COLLATE=" locale;
lc_ctype = "LC_CTYPE=" locale;
lc_messages = "LC_MESSAGES=" locale ;
lc_all =  "LC_ALL=" locale | empty; 
lang = "LANG=" locale;
posix = "POSIXLY_CORRECT=1" ;
locale = "en_NZ" | "nl_NL.UTF-8" | "pt_BR.UTF-8" | "fr_CH.ISO8859-15" | "eu_ES.ISO8859-15" | "en_US.US-ASCII" | "af_ZA" | "bg_BG" | "cs_CZ.UTF-8" | "fi_FI" | "zh_CN.UTF-8" | "eu_ES" | "sk_SK.ISO8859-2" | "nl_BE" | "fr_BE" | "sk_SK" | "en_US.UTF-8" | "en_NZ.ISO8859-1" | "de_CH" | "sk_SK.UTF-8" | "de_DE.UTF-8" | "am_ET.UTF-8" | "zh_HK" | "be_BY.UTF-8" | "uk_UA" | "pt_PT.ISO8859-1" | "en_AU.US-ASCII" | "kk_KZ.PT154" | "en_US" | "nl_BE.ISO8859-15" | "de_AT.ISO8859-1" | "hr_HR.ISO8859-2" | "fr_FR.ISO8859-1" | "af_ZA.UTF-8" | "am_ET" | "fi_FI.ISO8859-1" | "ro_RO.UTF-8" | "af_ZA.ISO8859-15" | "en_NZ.UTF-8" | "fi_FI.UTF-8" | "hr_HR.UTF-8" | "da_DK.UTF-8" | "ca_ES.ISO8859-1" | "en_AU.ISO8859-15" | "ro_RO.ISO8859-2" | "de_AT.UTF-8" | "pt_PT.ISO8859-15" | "sv_SE" | "fr_CA.ISO8859-1" | "fr_BE.ISO8859-1" | "en_US.ISO8859-15" | "it_CH.ISO8859-1" | "en_NZ.ISO8859-15" | "en_AU.UTF-8" | "de_AT.ISO8859-15" | "af_ZA.ISO8859-1" | "hu_HU.UTF-8" | "et_EE.UTF-8" | "he_IL.UTF-8" | "uk_UA.KOI8-U" | "be_BY" | "kk_KZ" | "hu_HU.ISO8859-2" | "it_CH" | "pt_BR" | "ko_KR" | "it_IT" | "fr_BE.UTF-8" | "ru_RU.ISO8859-5" | "zh_TW" | "zh_CN.GB2312" | "no_NO.ISO8859-15" | "de_DE.ISO8859-15" | "en_CA" | "fr_CH.UTF-8" | "sl_SI.UTF-8" | "uk_UA.ISO8859-5" | "pt_PT" | "hr_HR" | "cs_CZ" | "fr_CH" | "he_IL" | "zh_CN.GBK" | "zh_CN.GB18030" | "fr_CA" | "pl_PL.UTF-8" | "ja_JP.SJIS" | "sr_YU.ISO8859-5" | "be_BY.CP1251" | "sr_YU.ISO8859-2" | "sv_SE.UTF-8" | "sr_YU.UTF-8" | "de_CH.UTF-8" | "sl_SI" | "pt_PT.UTF-8" | "ro_RO" | "en_NZ.US-ASCII" | "ja_JP" | "zh_CN" | "fr_CH.ISO8859-1" | "ko_KR.eucKR" | "be_BY.ISO8859-5" | "nl_NL.ISO8859-15" | "en_GB.ISO8859-1" | "en_CA.US-ASCII" | "is_IS.ISO8859-1" | "ru_RU.CP866" | "nl_NL" | "fr_CA.ISO8859-15" | "sv_SE.ISO8859-15" | "hy_AM" | "en_CA.ISO8859-15" | "en_US.ISO8859-1" | "zh_TW.Big5" | "ca_ES.UTF-8" | "ru_RU.CP1251" | "en_GB.UTF-8" | "en_GB.US-ASCII" | "ru_RU.UTF-8" | "eu_ES.UTF-8" | "es_ES.ISO8859-1" | "hu_HU" | "el_GR.ISO8859-7" | "en_AU" | "it_CH.UTF-8" | "en_GB" | "sl_SI.ISO8859-2" | "ru_RU.KOI8-R" | "nl_BE.UTF-8" | "et_EE" | "fr_FR.ISO8859-15" | "cs_CZ.ISO8859-2" | "lt_LT.UTF-8" | "pl_PL.ISO8859-2" | "fr_BE.ISO8859-15" | "is_IS.UTF-8" | "tr_TR.ISO8859-9" | "da_DK.ISO8859-1" | "lt_LT.ISO8859-4" | "lt_LT.ISO8859-13" | "zh_TW.UTF-8" | "bg_BG.CP1251" | "el_GR.UTF-8" | "be_BY.CP1131" | "da_DK.ISO8859-15" | "is_IS.ISO8859-15" | "no_NO.ISO8859-1" | "nl_NL.ISO8859-1" | "nl_BE.ISO8859-1" | "sv_SE.ISO8859-1" | "pt_BR.ISO8859-1" | "zh_CN.eucCN" | "it_IT.UTF-8" | "en_CA.UTF-8" | "uk_UA.UTF-8" | "de_CH.ISO8859-15" | "de_DE.ISO8859-1" | "ca_ES" | "sr_YU" | "hy_AM.ARMSCII-8" | "ru_RU" | "zh_HK.UTF-8" | "eu_ES.ISO8859-1" | "is_IS" | "bg_BG.UTF-8" | "ja_JP.UTF-8" | "it_CH.ISO8859-15" | "fr_FR.UTF-8" | "ko_KR.UTF-8" | "et_EE.ISO8859-15" | "kk_KZ.UTF-8" | "ca_ES.ISO8859-15" | "en_IE.UTF-8" | "es_ES" | "de_CH.ISO8859-1" | "en_CA.ISO8859-1" | "es_ES.ISO8859-15" | "en_AU.ISO8859-1" | "el_GR" | "da_DK" | "no_NO" | "it_IT.ISO8859-1" | "en_IE" | "zh_HK.Big5HKSCS" | "hi_IN.ISCII-DEV" | "ja_JP.eucJP" | "it_IT.ISO8859-15" | "pl_PL" | "ko_KR.CP949" | "fr_CA.UTF-8" | "fi_FI.ISO8859-15" | "en_GB.ISO8859-15" | "fr_FR" | "hy_AM.UTF-8" | "no_NO.UTF-8" | "es_ES.UTF-8" | "de_AT" | "tr_TR.UTF-8" | "de_DE" | "lt_LT" | "tr_TR" | "C" | "POSIX";
empty = "";
command = symbolic_link_options starting_point find_expression_or_empty;
symbolic_link_options = " -H" | " -L" | " -P" | empty;
debugopts = debug_options | debug_options "," debugopts;
debug_options = "exec" | "opt" | "rates" | "search" | "stat" | "tree" | "all"  | "help";
starting_point = empty | ws starting_dir_list;
starting_dir_list = pathname | pathname ws starting_dir_list;
find_expression_or_empty = empty | ws find_expression;
find_expression = expr | " \\( " find_expression " \\) " | unary_operator find_expression | expr binary_operator find_expression;
unary_operator = "! " | "-not ";
binary_operator = " -a " | " -and " | " -or " | " -o " | " , " | ws;
expr = glob_opts | test_opts | posit_opts | actions;
glob_opts = depth | readdir_race | noleaf | min_depth | max_depth | no_descend ;
depth = "-d" | "-depth" ;
readdir_race = "-noignore_readdir_race" | "-ignore_readdir_race";
noleaf = "-noleaf";
min_depth = "-mindepth " levels;
max_depth = "-maxdepth " levels;
no_descend = "-xdev" |  "-mount";
levels = digits;
posit_opts = "-daystart" | "-follow" | warn_or_nowarn;
warn_or_nowarn = "-warn" | "-nowarn";
test_opts = last_accessed | last_modified | last_status | file_properties | match |  bool;  
last_accessed = "-amin " numeric_arg | "-anewer " reference | "-atime " numeric_arg;
last_status = "-cmin " numeric_arg | "-cnewer " reference | "-ctime " numeric_arg;
last_modified = "-mmin " numeric_arg | "-newer " reference | "-mtime " numeric_arg | "-newer" time_stamp_x time_stamp_y " " reference;
file_properties = "-empty" | "-fstype " filesystem_type | file_group | "-inum " numeric_arg | "-links " numeric_arg | "-samefile " name | "-size " numeric_arg space_unit | "-size " numeric_arg | "-type " file_type | "-xtype " file_type | "-uid " numeric_arg | "-used " numeric_arg | "-user " uname;
file_group = "-gid " numeric_arg | "-group " gname | "-nogroup" | "-nouser" ;
match = match_option | match_option ws match;
match_option = match_opts pattern;
match_opts = "-ilname " | "-iname " | "-ipath " | "-iregex " | "-iwholename " | "-lname " | "-name " | "-path " | "-regex " |  "-wholename ";
bool = "-true" | "-false";
time_stamp_x = "a" | "B" | "c" | "m" | "t";
time_stamp_y = "a" | "B" | "c" | "m" | "t";
space_unit = "b" | "c" | "w" | "k" | "M" | "G";
sign = "+" | "-" ;
numeric_arg = sign non_negative_integer | non_negative_integer ;
file_type = "b" | "c" | "d" | "p" | "f" | "l" | "s";
actions = "-exec " exec_bash_command " \\;" | "-exec " exec_bash_command_no_arg " {} +" | "-execdir " exec_bash_command " \\;" | "-execdir " exec_bash_command " \\;" | "-execdir " exec_bash_command_no_arg " {} +" | "-fls " pathname | "-fprint " pathname | "-fprint0 " pathname | "-fprintf " pathname " " format | "-ls" | "-print" | "-print0" | "-printf " format | "-prune" | "-quit";
exec_bash_command = "pwd" | "ls {}";
exec_bash_command_no_arg = "pwd" | "ls";
format = "'" format_string "'";
format_string = format_char | format_char format_string;
format_char = "\\" character | "%" character | " ";
filesystem_type = "ufs" | "4.2" | "4.3" | "nfs" | "tmp" | "mfs" | "S51K" | "S52K";
name = digits;
gname = digits;
non_negative_integer = digits;
uname = digits;
reference =  pathname;


ws = " ";
#include "regex.bnf"